version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.2
    - 10.1.3
  - dependency-name: swr
    versions:
    - 0.4.1
    - 0.4.2
    - 0.5.0
    - 0.5.2
    - 0.5.3
    - 0.5.4
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.5
